# Generated by Django 6.1.1 on 2026-10-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('initial_cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('snaptrade_user_id', models.CharField(blank=True, max_length=100)),
                ('snaptrade_account_id', models.CharField(blank=True, max_length=100)),
                ('snaptrade_user_secret', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'porfolios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('positions_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('daily_return', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('cumulative_return', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'performance_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['portfolio', 'date'], name='performance_portfol_321b6f_idx')],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('average_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unrealised_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unrealised_pnl_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock')),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['-current_value'],
                'unique_together': {('portfolio', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('filled_quantity', models.IntegerField(default=0)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('FILLED', 'Filled'), ('PARTIALLY_FILLED', 'Partially Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('external_order_id', models.CharField(blank=True, max_length=100)),
                ('snaptrade_order_id', models.CharField(blank=True, max_length=100)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolio.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', 'status'], name='trades_portfol_5c541d_idx'), models.Index(fields=['status', 'created_at'], name='trades_status_edb12f_idx')],
            },
        ),
    ]
